/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"

	"github.com/spf13/cobra"
)

// newSSHCommand writes an ssh_config and execs ssh so the same connection
// works for terminals, scp/rsync, VS Code Remote-SSH and JetBrains Gateway.
func newSSHCommand() *cobra.Command {
	var namespace string
	var gatewayAddr string
	var gatewayUser string
	var hostCAPath string
	var printConfig bool
	cmd := &cobra.Command{
		Use:   "ssh <sandbox>",
		Short: "SSH into a sandbox through the gateway",
		Args:  cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			target := args[0]
			if namespace != "" {
				target = args[0] + "." + namespace
			}
			cfgPath, err := writeSSHConfig(gatewayAddr, gatewayUser, hostCAPath)
			if err != nil {
				return err
			}
			if printConfig {
				fmt.Println(cfgPath)
				return nil
			}
			return execSSH(cfgPath, target)
		},
	}
	cmd.Flags().StringVarP(&namespace, "namespace", "n", "",
		"Sandbox namespace (appended as <sandbox>.<namespace>).")
	cmd.Flags().StringVar(&gatewayAddr, "gateway",
		envOr("KUBEPARK_GATEWAY", "localhost:2222"), "Gateway host:port.")
	cmd.Flags().StringVar(&gatewayUser, "gateway-user",
		envOr("KUBEPARK_GATEWAY_USER", "jump"), "Gateway SSH user.")
	cmd.Flags().StringVar(&hostCAPath, "host-ca", "",
		"Path to the host CA public key (adds an @cert-authority known_hosts entry).")
	cmd.Flags().BoolVar(&printConfig, "print-config", false,
		"Write the ssh_config and print its path instead of connecting.")
	return cmd
}

// writeSSHConfig renders ~/.kubepark/ssh_config. The gateway is a ProxyJump;
// the final hop uses the CLI certificate and (optionally) trusts the host
// CA so there is no host-key TOFU prompt.
func writeSSHConfig(gatewayAddr, gatewayUser, hostCAPath string) (string, error) {
	dir, err := configDir()
	if err != nil {
		return "", err
	}
	priv, _, err := ensureKeyPair()
	if err != nil {
		return "", err
	}
	cert, err := certPath()
	if err != nil {
		return "", err
	}

	gwHost, gwPort := splitHostPort(gatewayAddr)
	knownHosts := ""
	if hostCAPath != "" {
		khPath := filepath.Join(dir, "known_hosts")
		caPub, readErr := os.ReadFile(hostCAPath)
		if readErr != nil {
			return "", fmt.Errorf("read host CA: %w", readErr)
		}
		entry := append([]byte("@cert-authority * "), caPub...)
		if writeErr := os.WriteFile(khPath, entry, 0o644); writeErr != nil {
			return "", writeErr
		}
		knownHosts = "    UserKnownHostsFile " + khPath + "\n    StrictHostKeyChecking yes\n"
	} else {
		knownHosts = "    StrictHostKeyChecking accept-new\n"
	}

	gwKnownHosts := filepath.Join(dir, "known_hosts")
	// The wildcard must exclude the jump host itself, or ssh applies
	// ProxyJump to the gateway and recurses forever. The jump host is a
	// fixed, admin-controlled endpoint, so TOFU (accept-new) is acceptable
	// for it; sandbox host keys are always CA-verified.
	cfg := fmt.Sprintf(`# Generated by kubepark; do not edit.
Host kubepark-gateway
    HostName %s
    Port %s
    User %s
    IdentityFile %s
    IdentitiesOnly yes
    UserKnownHostsFile %s
    StrictHostKeyChecking accept-new

Host * !kubepark-gateway
    ProxyJump kubepark-gateway
    IdentityFile %s
    CertificateFile %s
    IdentitiesOnly yes
    ConnectTimeout 180
%s`, gwHost, gwPort, gatewayUser, priv, gwKnownHosts, priv, cert, knownHosts)

	cfgPath := filepath.Join(dir, "ssh_config")
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o600); err != nil {
		return "", err
	}
	return cfgPath, nil
}

// execSSH replaces the process with ssh -F <config> <target>.
func execSSH(cfgPath, target string) error {
	sshPath, err := exec.LookPath("ssh")
	if err != nil {
		return fmt.Errorf("ssh not found on PATH: %w", err)
	}
	args := []string{"ssh", "-F", cfgPath, target}
	return syscall.Exec(sshPath, args, os.Environ())
}

func splitHostPort(addr string) (host, port string) {
	host = addr
	port = "2222"
	for i := len(addr) - 1; i >= 0; i-- {
		if addr[i] == ':' {
			host = addr[:i]
			port = addr[i+1:]
			break
		}
	}
	if host == "" {
		host = "localhost"
	}
	return host, port
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
