---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepark.sinoa.jp
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepark.sinoa.jp
  resources:
  - sandboxes/finalizers
  verbs:
  - update
- apiGroups:
  - kubepark.sinoa.jp
  resources:
  - sandboxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubepark.sinoa.jp
  resources:
  - sandboxtemplates
  verbs:
  - get
  - list
  - watch
