# This rule is not used by the project kubepark itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kubepark.sinoa.jp.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-admin-role
rules:
- apiGroups:
  - kubepark.sinoa.jp
  resources:
  - sandboxes
  verbs:
  - '*'
- apiGroups:
  - kubepark.sinoa.jp
  resources:
  - sandboxes/status
  verbs:
  - get
