apiVersion: kubepark.sinoa.jp/v1alpha1
kind: SandboxTemplate
metadata:
  labels:
    app.kubernetes.io/name: kubepark
    app.kubernetes.io/managed-by: kustomize
  name: sandboxtemplate-sample
spec:
  image: kubepark/sandbox-ssh:latest
  terminationGracePeriodSeconds: 60
  container:
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
